### ISSUE TITLE
Alpha version fails with existing event.

### ISSUE THREAD

**Issue by Hallsworthb** [moderntribe/events-gutenberg#219]
Hi; I have installed Gutenberg on my development site - https://hallsworthb.uk
I tried to edit the first event but a totally blank page was displayed.
Showed events again and that item has Gutenberg against it, but going to it again just shows the same blank page.
Wordpress + OceanWP Theme + Elementor + Gutenberg
MacOS - Latest version (High Sierra)

**Comment by bordoni** [comment]
Hi @Hallsworthb, 

Thanks for reporting the Bug, there are some questions I need to answer to be able to debug and reproduce it here on our dev Environment.

- Which version of the Gutenberg Plugin are you using?
- Which version of our Extension are you using?
- Did you download those said versions from the ZIP files or using the GitHub repository?


Thanks again for posting this issue, hopefully, we can reproduce it here and fix it for everyone.

**Comment by Hallsworthb** [comment]
Hi

Thanks for the response

- gutenburg 3.4.0
- events-gutenberg-0.2.5 - alpha
- Gutenberg was flagged for download within Wordpress, which then flagged up your plugin. Downloaded both from within Wordpress.

I Hope this helps :)

Regards
Bob

**Comment by bordoni** [comment]
Hi @Hallsworthb,
We just resolved that issue on the latest version of our extension `0.2.6-alpha`, we are now compatible with version `3.5.0` of the Gutenberg Plugin.

Would you mind confirming if it fixed your problem?

**Comment by mitogh** [comment]
Yes, sorry at the moment the plugin is only being distributed via GitHub, you can find the latest releases with access to the ZIP files here:

- https://github.com/moderntribe/events-gutenberg/releases

Let us know how that goes.

Thank you!

**Comment by Hallsworthb** [comment]
Hi;
No, sorry. Deleted 0.2.5-Alpha, Installed 0.2.6-Alpha. Same result.
Cleared Caches / Closed and reopened browser (Safari) no change.

Regards
Bob

**Comment by mitogh** [comment]
Thank you.

I was able to replicate this problem with the latest version of Gutenberg and The Events Calendar extension for Gutenberg, however the issue is coming from Gutenberg instead as I tried to create a new post by disabling The Events Calendar extension and just use Gutenberg plugin alone, to create a new post. So latest version of Gutenberg has an issue with safari as this propagates into The Events Calendar extension.

Will try to follow up from this into the Gutenberg repository and try to update on this ticket as soon as we do have an update, to see if they have identify this issue already on the latest version of Gutenberg. 

In the meantime I suggest to try the extension or Gutenberg in a different browser vendor.

Thanks

**Comment by mitogh** [comment]
Ticket to follow up #8891

**Comment by Hallsworthb** [comment]
Chrome on iPhone also fails in the same way
Bob

**Comment by Hallsworthb** [comment]
Firefox on iPhone too. 
Bob

**Comment by Hallsworthb** [comment]
Hi;

Just to let you know - it is working now with Safari. Haven’t tried others, but I would guess they will be fine if Safari is!
Gutenberg 3.6.2
The Events calendar 0.2.6-Alpha

Regards
Bob

**Comment by Hallsworthb** [comment]
Hi;

Sorry - having said it was OK now, I find that imports all say “All Day” for the time.
However when I click on that part of the heading, it picks up the time as entered?

Is there a way to do that in bulk?

Regards
Bob

**Comment by bordoni** [comment]
Hi @Hallsworthb,

I am very glad that bug was fixed for you, sorry for the huge delay on the answer.

Can you try again with the latest version? We fixed a ton of problems around the date picker and the All day behavior.

If the problem persists, you can either re-open the issue or just open a new one.

Thanks a lot for reporting these problems.
