### ISSUE TITLE
Event Date Time bug

### ISSUE THREAD

**Issue by shadox** [moderntribe/events-gutenberg#270]
Hello,
I tried The Events Calendar + Gutenberg for a french project and I encountered a bug in the date selection :
https://gyazo.com/59760bcab570552917e9d896c3e59d1d
I think that the module does not correctly take into account the date parameters. Can you look ?
Nice work and sorry for my english.

**Comment by bordoni** [comment]
Hi @shadox,

Would you mind sharing with us which version of the Gutenberg plugin and our Extension you are using?

Would you mind also sharing what is your Date Format in the `Events > Settings > Display` page?

My Best Regards,

**Comment by shadox** [comment]
Hi @bordoni,

I'm using : 
- Wordpress 4.9.8-fr_FR
- Gutenberg 3.6.2
- The Events Calendar: Gutenberg Extension - Version 0.2.6-alpha.

My global setting (french language) :
https://gyazo.com/40057c47f3e3f44f10c3453f608861fd

My events calendar setting :
https://gyazo.com/867f531517b2618df8c743811acdd7bc

Thx a lot.

**Comment by kent1D** [comment]
We encounter a similar problem with similar settings

**Comment by kent1D** [comment]
is there a workaround to make the date selector working? we have the last versions of Gutenberg (3.9.0) and events-gutenberg (0.2.9-alpha)

**Comment by bordoni** [comment]
Hi @shadox and @kent1D,
We finally figured out why that bug was happening, thanks a lot for reporting it to us.

Tomorrow we will release `0.3.0-alpha` which contains #359 that solves a problem created by an option on The Events Calendar plugin that was breaking the Gutenberg extension on Events.

Hopefully it will fix your problems, otherwise please don't hesitate to open another issue.
