### ISSUE TITLE
Multiple RSVP per events

### ISSUE THREAD

**Issue by garthh** [moderntribe/events-gutenberg#461]
Hi, non-Gutenberg version can get multiple RSVP for a same event.
It's impossible with the Gutenberg editor, will this functionality be available ?
When I add manualy in my database more RSVP data (it's very very very long), I get multiple RVSP on event in my site, but only the last RSVP is visible in editor.

A great thank for your great work !

**Comment by garthh** [comment]
I use Event Calendar to inform for RPG events, and we offer multiple RPG table on a same envent
For example : this one with Events-Gutenberg (I've duplicate tickets in my database, but I only have one "gutenberg block" on my backend)
https://portes-imaginaire.org/evenement/gamein-reims-2018/
and this one with classical editor
https://portes-imaginaire.org/evenement/jidevoyelles-2-harry-potter/

**Comment by garthh** [comment]
Hi, I've tryed with free tickets instead of RSVP, but users are redirect to paypal with a ticket price at 0€ (and they can't record their venue). 
Best,
Garthh

**Comment by bordoni** [comment]
Uhnn that is weird, I feel like what you are saying there is a Bug that we do not have on our systems, I will ask QA to confirm later and we will track it as a bug so you can have Free Tickets.

**Comment by leahkoerper** [comment]
Hi garthh,

If you are using Event Tickets without the premium add-on Event Tickets Plus, it's not possible to do free tickets because of limitations in PayPals system. You have a couple of options here:

* Continue to use the classic editor for setting up events with RSVPs so that you can set up multiples
* Purchase a license to Event Tickets Plus so that you can use the attendee registration options to have people RSVP and choose a table for the event.
* Purchase a license to Event Tickets Plus so that you can create free tickets with different ticket types and thus allow people to choose a specific table.

Best,
Leah
