### ISSUE TITLE
Google Maps on Venue not working as Expect

### ISSUE THREAD

**Issue by bordoni** [moderntribe/events-gutenberg#9]
Sometimes when loading the Google Maps instance it doesn't load properly or when changing the Venue the Marker will not be placed properly.

Seems to be a bug created by the Package we are depending on, or my ignorance on how React Components are supposed to update, keep in mind this is all Async due to Google Geocoding.

**Comment by nealfennimore** [comment]
I have a hunch that this may be due to reassigning state references before setting them. Should probably just declare a new variable, and then send it into `setState`
https://github.com/moderntribe/events-gutenberg/blob/master/src/modules/elements/google-map.js#L186
https://github.com/moderntribe/events-gutenberg/blob/master/src/modules/elements/google-map.js#L193

**Comment by bordoni** [comment]
We finally fixed that on the latest release of the Venue Block.
http://i.bordoni.me/tDAL
